version: '3.2'

services:
  ahmia-index:
    container_name: "ahmia-index"
    image: dapperblondie/ahmia-index:1.0
    depends_on:
      - elasticsearch1

  ahmia-crawler:
    container_name: "ahmia-crawler"
    image: dapperblondie/ahmia-crawler:1.0
    depends_on:
      - ahmia-index
      - tor-privoxy-web
      - tor-privoxy0
      - tor-privoxy1
      - tor-privoxy2
      - tor-privoxy3
      - tor-privoxy4
      - tor-privoxy5
      - tor-privoxy6
      - tor-privoxy7
      - tor-privoxy8
      - tor-privoxy9

  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    restart: always
    environment:
      - "ES_JAVA_OPTS=-Xmx2g -Xms2g"
      - network.host=0.0.0.0
      - discovery.seed_hosts=elasticsearch1
      - indices.query.bool.max_clause_count=10240
      - cluster.initial_master_nodes=elasticsearch1
      - node.name=elasticsearch1
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch1:/var/lib/elasticsearch/data
    ports:
      - "127.0.0.1:9201:9200"
    container_name: "ahmia-elasticsearch1"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.0
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch1:9200
      - NODE_OPTIONS="--max-old-space-size=8192"  
      - elasticsearch.requestTimeout=300000 
      - elasticsearch.startupTimeout=500000  
    depends_on:
      - elasticsearch1
    ports:
      - "127.0.0.1:5602:5601"
    container_name: "ahmia-kibana"

  tor-privoxy0:
    restart: always
    image: dapperblondie/darkweb-search-engine-tor-privoxy0
    container_name: "ahmia-engine-tor-privoxy0"
  tor-privoxy1:
    restart: always
    image: dapperblondie/darkweb-search-engine-tor-privoxy0
    container_name: "ahmia-engine-tor-privoxy1" 
  tor-privoxy2:
    restart: always
    image: dapperblondie/darkweb-search-engine-tor-privoxy0
    container_name: "ahmia-engine-tor-privoxy2"
  tor-privoxy3:
    restart: always
    image: dapperblondie/darkweb-search-engine-tor-privoxy0
    container_name: "ahmia-engine-tor-privoxy3"
  tor-privoxy4:
    restart: always
    image: dapperblondie/darkweb-search-engine-tor-privoxy0
    container_name: "ahmia-engine-tor-privoxy4"
  tor-privoxy5:
    restart: always
    image: dapperblondie/darkweb-search-engine-tor-privoxy0
    container_name: "ahmia-engine-tor-privoxy5"
  tor-privoxy6:
    restart: always
    image: dapperblondie/darkweb-search-engine-tor-privoxy0
    container_name: "ahmia-engine-tor-privoxy6"
  tor-privoxy7:
    restart: always
    image: dapperblondie/darkweb-search-engine-tor-privoxy0
    container_name: "ahmia-engine-tor-privoxy7"
  tor-privoxy8:
    restart: always
    image: dapperblondie/darkweb-search-engine-tor-privoxy0
    container_name: "ahmia-engine-tor-privoxy8"
  tor-privoxy9:
    restart: always
    image: dapperblondie/darkweb-search-engine-tor-privoxy0
    container_name: "ahmia-engine-tor-privoxy9"   
    
  tor-privoxy-web:
    restart: always
    hostname: privoxy
    image: dapperblondie/darkweb-search-engine-tor-privoxy-web
    ports:
      # - "9050:9050" # Tor proxy
      - "127.0.0.1:3101:8100" # Privoxy
    container_name: "ahmia-search-engine-tor-privoxy-web"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.56.0/24
