version: '3.2'

services:
  ahmia-index:
    container_name: "ahmia-index"
    image: dapperblondie/ahmia-index:4.0
    depends_on:
      - elasticsearch1

  ahmia-crawler:
    container_name: "ahmia-crawler"
    image: dapperblondie/ahmia-crawler:4.0
    depends_on:
      - ahmia-index

  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    restart: always
    environment:
      - "ES_JAVA_OPTS=-Xmx2g -Xms2g"
      - network.host=0.0.0.0
      - discovery.seed_hosts=elasticsearch1
      - indices.query.bool.max_clause_count=10240
      - cluster.initial_master_nodes=elasticsearch1
      - node.name=elasticsearch1
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch1:/var/lib/elasticsearch/data
      - ./elk-certs:/usr/share/elasticsearch/config/certificates
    ports:
      - "127.0.0.1:9201:9200"
    container_name: "ahmia-elasticsearch1"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.0
    restart: always
    environment:
     - ELASTICSEARCH_URL=http://elasticsearch1:9200
     - ELASTICSEARCH_HOSTS=http://elasticsearch1:9200
     - server.publicBaseUrl
     - NODE_OPTIONS="--max-old-space-size=8192"
     - elasticsearch.requestTimeout=300000 
     - elasticsearch.startupTimeout=500000
    depends_on:
      - elasticsearch1
    volumes:
      - ./elk-certs:/usr/share/elasticsearch/config/certificates
    ports:
      - "127.0.0.1:5602:5601"
    container_name: "ahmia-kibana"

networks:
  ahmia-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.56.0/24
